### PR TITLE
SI-470 workaround: Implicitly adding 15 minutes to test timeout

### PR DESCRIPTION
**Pull request by michaelk-stratoscale**
@Stratoscale/systegration

### CODE REVIEW

**Comment by michaelk-stratoscale** [comment]
@Stratoscale/systegration 
Let me ship...

**Comment by sergey-stratoscale** [comment]
@michaelk-stratoscale if you're not adding an explicit timeout for the teardown, please change the timeout here instrad:
https://github.com/Stratoscale/monkey/blob/v2.0/py/strato/tests/monkeytest.py#L96

**Comment by rom-stratoscale** [comment]
See @sergey-stratoscale answer. That what I meant during the daily

**Comment by eliran-stratoscale** [comment]
@michaelk-stratoscale I would prefer if you do this in monkey and not here.

**Comment by michaelk-stratoscale** [comment]
@Stratoscale/systegration 
Moved the fix to monkeytest as suggested and pushed.
Closing this one.

**Pull request closed without merging**
